version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=51.15.115.36,localhost,OH,127.0.0.1
      - DJANGO_SETTINGS_MODULE=discussit.settings
      - ENVIRONMENT=production
      - DEBUG=False
      - SECRET_KEY=SN4gyHH97gZdWBq_XVKY4B1FzMC-UG1drfIU98Kwf08ETOv7yLJahSUGhoC9QIhzf-0
      - CORS_ALLOWED_ORIGINS=http://51.15.115.36:8000,http://localhost:4200,http://127.0.0.1:4200
      - CSRF_TRUSTED_ORIGINS=http://51.15.115.36,http://localhost
      - DATABASE_URL=postgres://discussit_user:discussit_password_2024@localhost:5432/discussit
    command: gunicorn --config gunicorn_config.py discussit.wsgi:application
    volumes:
      - .:/usr/src/app
